### ISSUE TITLE
Attribute not created when added in an already existing model

### ISSUE THREAD

**Issue by rcasteran** [rcasteran/jarvis4se#29]
**Impacted version**
jarvis4se version: 1.1.3

**Describe the bug**
Taking an already existing model without an attribute.
When creating an new attribute, Jarvis indicates that it is created without any errors. But the xml is not containing it.
When trying to assign it a value, Jarvis does nothing without showing an error.

**To Reproduce**
Assuming that test is a model containing a single function F1
Execute the followings commands:
```
%%jarvis
with test
a is an attribute
```
Jarvis indicates:
_test.xml parsed
a is an attribute (added)
test.xml updated_
```
%%jarvis
with test
The a of F1 is "toto"
```
Jarvis indicates:
_test.xml parsed_

**Expected behavior**
Jarvis must create the attribute in the xml file

**Desktop (please complete the following information):**
- Browser: Chrome
- Browser version: 100.0.4896.75
- Java: JRE
- Java version: 1.8.0_291

**Comment by Not2behere** [comment]
A workaround for this :

1. Delete existing .xml file
2. Rerun your notebook(restart kernel + run all cells) with the new Jarvis version

This is due to the fact that at the root of the xml : <attributeList/> has been added in 1.1.3. and wasn't there before. So in your .xml made from previous version jarvis cannot find this tag.
