### ISSUE TITLE
New XML structure

### ISSUE THREAD

**Issue by rcasteran** [rcasteran/jarvis4se#40]
**Is your feature request related to a problem? Please describe.**
Jarvis generates a XML file with "funcarch" as a root node.
This does not allow to add the elements describing the physical architecture of the system.

**Describe the solution you'd like**
- Restructure the XML file in according with [3SE datamodel](https://github.com/rcasteran/3se) to add new concepts such as physical architecture of the system
- Allow Jarvis to automatically update on old XML structure ("funcarch" as a root node") into the new one ("systemAnalysis" as a root node)

**Describe alternatives you've considered**
None

**Comment by Not2behere** [comment]
Regarding this : "Allow Jarvis to automatically update on old XML structure ("funcarch" as a root node") into the new one ("systemAnalysis" as a root node)"
Since there is not so much user (at the moment ;) ), the easiest and more convenient way (from dev side) would be to delete old xml file an (re)run the whole notebook. Otherwise, a specific module/script has to be developped. If there is a "real" need for this feature please let me know.

**Comment by rcasteran** [comment]
Ok, as long as Jarvis takes no action and displays an error message in case of old xml structure found
